In [10]:
with open("./input.txt", "r",encoding="utf-8") as file:
    data = file.read()
    # print(data)
import torch

voc=sorted(list(set(data)))
# print(len(data))
# print(list(set(data)))
# print(set(data))
# print(voc)
chtoi={c:i for i,c in enumerate(voc)}
itoch={i:c for i,c in enumerate(voc)}
encoding=lambda s: [chtoi[c] for c in s]
decoding=lambda s: "".join([itoch[c] for c in s])


# print(encoding("hello world"))
# print(decoding(encoding("hello world")))

datatset=torch.tensor(encoding(data),dtype=torch.long)
# print(datatset[:100])
n=int(0.9*len(datatset))
trainset=datatset[:n]
testset=datatset[n:]
block_size=8
x_train=datatset[:block_size+1]
y_train=datatset[1:block_size+1]
# print(x_train)
for i in range(block_size):
    context=x_train[:i+1]
    target=y_train[i]
    # print(f"context: {context}, target: {target}")
torch.manual_seed(42)
batch_size=4
block_size=8
def getbatch(split):
    data=trainset if split=="train" else testset
    ix=torch.randint(len(data)-block_size,(batch_size,))
    x=torch.stack(([data[i:i+block_size] for i in ix]))
    y=torch.stack(([data[i+1:i+block_size+1] for i in ix]))
    # print(ix)
    return x,y
xb,yb=getbatch("train")
print(xb)
print(yb)

for b in range(batch_size):
    for a in range(block_size):
        context=xb[b,:a+1]
        target=yb[b,a]
        print(f"context: {context}, target: {target}")
    


tensor([[57,  1, 46, 47, 57,  1, 50, 53],
        [ 1, 58, 46, 43, 56, 43,  1, 41],
        [17, 26, 15, 17, 10,  0, 32, 53],
        [57, 58,  6,  1, 61, 47, 58, 46]])
tensor([[ 1, 46, 47, 57,  1, 50, 53, 60],
        [58, 46, 43, 56, 43,  1, 41, 39],
        [26, 15, 17, 10,  0, 32, 53,  1],
        [58,  6,  1, 61, 47, 58, 46,  0]])
context: tensor([57]), target: 1
context: tensor([57,  1]), target: 46
context: tensor([57,  1, 46]), target: 47
context: tensor([57,  1, 46, 47]), target: 57
context: tensor([57,  1, 46, 47, 57]), target: 1
context: tensor([57,  1, 46, 47, 57,  1]), target: 50
context: tensor([57,  1, 46, 47, 57,  1, 50]), target: 53
context: tensor([57,  1, 46, 47, 57,  1, 50, 53]), target: 60
context: tensor([1]), target: 58
context: tensor([ 1, 58]), target: 46
context: tensor([ 1, 58, 46]), target: 43
context: tensor([ 1, 58, 46, 43]), target: 56
context: tensor([ 1, 58, 46, 43, 56]), target: 43
context: tensor([ 1, 58, 46, 43, 56, 43]), target: 1
context: tensor([ 

In [15]:
import torch 
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(42)
n_embd=32
block_size=8


In [27]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Head(nn.Module):
    """ One head of self-attention """

    def __init__(self, head_size,n_embd, block_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

    def forward(self, x):
        B, T, C = x.shape  

      
        k = self.key(x)  
        q = self.query(x)  
        wei = q @ k.transpose(-2, -1) * C**-0.5  
        
        # Apply the triangular mask
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))  
        
        wei = F.softmax(wei, dim=-1)  

        v = self.value(x)  
        out = wei @ v 

        return out


In [ ]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table=nn.Embedding(vocab_size,n_embd)
        self.positional_embedding_table=nn.Embedding(block_size,n_embd) # plus one for the initial padding token
        self.sa_head=Head( 32,n_embd,block_size)
    
        self.lm_head=nn.Linear(n_embd,vocab_size)
    def forward(self, xb,yb=None):
        B,T=xb.shape
        token_embedding=self.token_embedding_table(xb)
        pos_emb=self.token_embedding_table(torch.arange(T))
        # logits=self.lm_head(token_embedding)
        x=token_embedding+pos_emb
        x=self.sa_head(x)
        logits=self.lm_head(x)
      
        if yb is not None:
            B,C,T=logits.shape
            logits=logits.view(B*C,T)
            yb=yb.view(B*C)

            loss=F.cross_entropy(logits,yb)
        else:
            loss=None
        return logits,loss

    def generate(self, idx, max_new_tokens): 
        # idx is (B, T) array of indices in the current context 
        for _ in range(max_new_tokens):  
            # get the predictions 
            logits, loss = self(idx)  

            # focus only on the last time step 
            # print(logits)
            logits = logits[:, -1, :]  # becomes (B, C)  
            # print(logits)

            # apply softmax to get probabilities  
            probs = F.softmax(logits, dim=-1)  # (B, C)  

            # sample from the distribution  
            idx_next = torch.multinomial(probs, num_samples=1)  # (B, 1)  

            # append sampled index to the running sequence  
            idx = torch.cat((idx, idx_next), dim=1)  # (B, T+1) 
            # print(idx) 

        return idx

m=BigramLanguageModel(len(voc))
logit,loss=m(xb,yb)
# print(logit.shape)
# print(loss)
        
# print(len(voc))

print(decoding(m.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=100)[0].tolist()))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x8 and 32x65)

In [83]:
m.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=100)

tensor([[ 0, 16, 23, 34, 39, 51,  4, 23,  9, 38, 52, 49, 21, 25, 39, 55, 52, 58,
         48, 46,  7, 13, 35,  5, 14, 22, 62, 62, 45, 46, 48, 38, 32, 14, 15, 52,
         15, 33, 12, 55, 14, 29, 40, 61, 63, 15, 48, 46, 30, 46, 31, 24, 63, 22,
         44, 19, 58, 57, 59, 58, 22, 14, 63,  7, 48,  4,  6, 56,  6,  5, 49,  3,
         28, 32, 59, 38, 51,  9, 58, 28, 40, 59,  1, 26, 61, 20,  7, 21, 28, 43,
         39, 55, 59, 22, 34, 56, 23,  5, 62,  1, 44]])

In [84]:
len("""gBXCYUEBUkTrhlwhYvCHU3jVQWIOVFHSbBtlnSfFoHZK.nHR&AcjvfzzJ.K,HCYUui-xd
L;Wu3VnSgv.$afs
BqpdHVLgwcOwN """)

100

In [85]:
optimizer=torch.optim.AdamW(m.parameters(),lr=0.001)


In [86]:
batch_size = 32

for steps in range(10000):
    xb, yb = getbatch('train')
    logits, loss = m(xb, yb)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if steps % 100 == 0:
        print(f"Step {steps+1}, Loss: {loss.item():.4f}")


Step 1, Loss: 4.6977
Step 101, Loss: 4.5542
Step 201, Loss: 4.4854
Step 301, Loss: 4.3880
Step 401, Loss: 4.2180
Step 501, Loss: 4.2192
Step 601, Loss: 4.0598
Step 701, Loss: 3.9743
Step 801, Loss: 3.9993
Step 901, Loss: 3.9300
Step 1001, Loss: 3.7942
Step 1101, Loss: 3.8274
Step 1201, Loss: 3.5697
Step 1301, Loss: 3.4974
Step 1401, Loss: 3.5198
Step 1501, Loss: 3.3823
Step 1601, Loss: 3.4163
Step 1701, Loss: 3.3589
Step 1801, Loss: 3.3072
Step 1901, Loss: 3.2026
Step 2001, Loss: 3.1628
Step 2101, Loss: 3.0630
Step 2201, Loss: 3.1235
Step 2301, Loss: 2.9732
Step 2401, Loss: 3.0888
Step 2501, Loss: 2.9927
Step 2601, Loss: 2.8689
Step 2701, Loss: 2.9053
Step 2801, Loss: 2.9279
Step 2901, Loss: 2.8635
Step 3001, Loss: 2.8600
Step 3101, Loss: 2.9175
Step 3201, Loss: 2.7034
Step 3301, Loss: 2.7863
Step 3401, Loss: 2.7986
Step 3501, Loss: 2.6293
Step 3601, Loss: 2.7755
Step 3701, Loss: 2.7048
Step 3801, Loss: 2.6091
Step 3901, Loss: 2.5815
Step 4001, Loss: 2.6208
Step 4101, Loss: 2.6359
Step

In [87]:
print(decoding(m.generate(idx=torch.zeros((1,1),dtype=torch.long),max_new_tokens=100)[0].tolist()))


RY:
Yors t p kere isd, m INGea earusher Tistced.
Wharologo!


Whe hildy por byof?
GUFarastaldXIndesw


In [88]:
torch.manual_seed(42)
B,T,C=4,8,2
x=torch.randn(B,T,C)
xbow=torch.zeros(B,T,C)
print(x)
for b in range(B):
    for t in range(T):
        xprev=x[b,:t+1]
        xbow[b,t]=torch.mean(xprev,dim=0)


tensor([[[ 1.9269,  1.4873],
         [ 0.9007, -2.1055],
         [ 0.6784, -1.2345],
         [-0.0431, -1.6047],
         [-0.7521,  1.6487],
         [-0.3925, -1.4036],
         [-0.7279, -0.5594],
         [-0.7688,  0.7624]],

        [[ 1.6423, -0.1596],
         [-0.4974,  0.4396],
         [-0.7581,  1.0783],
         [ 0.8008,  1.6806],
         [ 1.2791,  1.2964],
         [ 0.6105,  1.3347],
         [-0.2316,  0.0418],
         [-0.2516,  0.8599]],

        [[-1.3847, -0.8712],
         [-0.2234,  1.7174],
         [ 0.3189, -0.4245],
         [ 0.3057, -0.7746],
         [-1.5576,  0.9956],
         [-0.8798, -0.6011],
         [-1.2742,  2.1228],
         [-1.2347, -0.4879]],

        [[-0.9138, -0.6581],
         [ 0.0780,  0.5258],
         [-0.4880,  1.1914],
         [-0.8140, -0.7360],
         [-1.4032,  0.0360],
         [-0.0635,  0.6756],
         [-0.0978,  1.8446],
         [-1.1845,  1.3835]]])


In [89]:
x[0],xbow[0]

(tensor([[ 1.9269,  1.4873],
         [ 0.9007, -2.1055],
         [ 0.6784, -1.2345],
         [-0.0431, -1.6047],
         [-0.7521,  1.6487],
         [-0.3925, -1.4036],
         [-0.7279, -0.5594],
         [-0.7688,  0.7624]]),
 tensor([[ 1.9269,  1.4873],
         [ 1.4138, -0.3091],
         [ 1.1687, -0.6176],
         [ 0.8657, -0.8644],
         [ 0.5422, -0.3617],
         [ 0.3864, -0.5354],
         [ 0.2272, -0.5388],
         [ 0.1027, -0.3762]]))

In [90]:
torch.manual_seed(42)
a=torch.tril(torch.ones(3,3,dtype=torch.float))
b=torch.randint(0,10,(3,2),dtype=torch.float)
c=a@b

In [91]:
a,b

(tensor([[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]),
 tensor([[2., 7.],
         [6., 4.],
         [6., 5.]]))

In [92]:
a=a/torch.sum(a,dim=1,keepdim=True)
# b=torch.sum(a,dim=1)

a

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])

In [93]:
v=torch.tril(torch.ones(T,T))
v=v/torch.sum(v,dim=1,keepdim=True)
v

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [94]:
# s=v/torch.sum(v,dim=1)
# s


In [95]:
wei=torch.tril(torch.ones(T,T))
wei=wei/torch.sum(wei,dim=1,keepdim=True)
xbow2=wei@x
wei.shape,x.shape


(torch.Size([8, 8]), torch.Size([4, 8, 2]))

In [96]:
xbow2.shape


torch.Size([4, 8, 2])

In [99]:
# tril=torch.tril(torch.ones(T,T))
wei=torch.zeros(T,T)
# tril,wei

In [100]:
wei=wei.masked_fill(tril==0,float("-inf"))
wei

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [101]:
wei=torch.softmax(wei,dim=1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [107]:
torch.manual_seed(42)
B,T,C=4,8,32
x=torch.randn(B,T,C)
head_size=16
key=nn.Linear(C,head_size,bias=False)
query=nn.Linear(C,head_size,bias=False)
value=nn.Linear(C,head_size,bias=False)
k=key(x)
q=query(x)
wei=q@k.transpose(-2,-1)

# tril=torch.tril(torch.ones(T,T))
# wei=torch.zeros(T,T)
wei=wei.masked_fill(tril==0,float("-inf"))
wei=torch.softmax(wei,dim=1)
v=value(x)
out=wei@v
out.shape

torch.Size([4, 8, 16])